# 项目配置文件
# 所有参数集中管理，便于修改和实验

# 数据相关配置
data:
  full_mimic_data_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/mimic/mimic_train_combined_static_dynamic.feather'  # 原始数据路径
  full_covid_data_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/covid/covid_combined_static_dynamic.feather'  # 原始数据路径
  full_eicu1_data_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/eicu1/eicu1_combined_static_dynamic.feather'  # 原始数据路径/covid_combined_static_dynamic.feather'  # 原始数据路径
  full_eicu2_data_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/eicu2/eicu2_combined_static_dynamic.feather'  # 原始数据路径

  index_label_mimic_train_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/mimic/mimic_train_sequence_data.pkl'
  index_label_mimic_val_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/mimic/mimic_val_sequence_data.pkl'
  index_label_mimic_test_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/mimic/mimic_test_sequence_data.pkl'
  index_label_covid_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/covid/covid_sequence_data.pkl'
  index_label_eicu1_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/eicu1/eicu1_sequence_data.pkl'
  index_label_eicu2_path: 'D:/Doctor_files/Projects/ELDER-sepsis_prog_timeseries/preprocessed data/eicu2/eicu2_sequence_data.pkl'

  drop_columns: ['subject_id', 'hadm_id', 'ethnicity', 'first_careunit', 'intime', 'outtime', 'los_icu_day', 'los_hospital_day', 'admittime', 'dischtime', 'deathtime', 'death_hosp', 'sepsis_time',
                 'deathtime_icu_day', 'deathtime_icu_hour', 'los_icu_admit_day', 'hospitalid', 'region', 'admission_type']         # 读入后需要删除的列
  MAX_SEQ_LEN: 180

# 训练相关配置
training:
  epochs: 10                              # 训练轮数
  input_dim:
  batch_size: 16                          # 批次大小
  learning_rate: 0.001                    # 学习率
  weight_decay: 0.00001                   # 权重衰减
#  task_weights: [1.0, 1.0, 0.1]           # 各任务损失权重 [死亡率, 分类, 回归]
  seed: 42                                # 随机种子
  result_dir: 'results'                   # 结果保存目录
  log_interval: 10                        # 日志打印间隔(批次)
  num_workers: 4                          # 数据加载线程数

